CREATE TABLE "User" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" varchar(150) NOT NULL,
    "Email" varchar(255) NOT NULL UNIQUE,
    "PasswordHash" varchar(500) NOT NULL,
    "ProfileImageUrl" varchar(500),
    "CreatedAt" timestamp NOT NULL
);

CREATE TABLE "Source" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "Name" varchar(150) NOT NULL,
    "ImageUrl" varchar(500),
    "CreatedAt" timestamp NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    CONSTRAINT "FK_Source_User" FOREIGN KEY ("UserId") REFERENCES "User" ("Id")
);

CREATE TABLE "TransactionType" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "Name" varchar(150) NOT NULL,
    "Color" varchar(150) NOT NULL,
    CONSTRAINT "UQ_TransactionType_User_Name" UNIQUE ("UserId", "Name"),
    CONSTRAINT "FK_TransactionType_User" FOREIGN KEY ("UserId") REFERENCES "User" ("Id")
);

CREATE TABLE "AccountType" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" varchar(100) NOT NULL
);

CREATE TABLE "Account" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "AccountTypeId" integer NOT NULL,
    "Name" varchar(150) NOT NULL,
    "BankName" varchar(150),
    "CardBrand" varchar(50),
    "Last4" varchar(4),
    "ImageUrl" varchar(500),
    "Color" varchar(50),
    "CreatedAt" timestamp NOT NULL,
    CONSTRAINT "FK_Account_User" FOREIGN KEY ("UserId") REFERENCES "User" ("Id"),
    CONSTRAINT "FK_Account_AccountType" FOREIGN KEY ("AccountTypeId") REFERENCES "AccountType" ("Id")
);

CREATE TABLE "TaskStatus" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "Name" varchar(100) NOT NULL,
    "Color" varchar(50) NOT NULL,
    "SortOrder" integer NOT NULL,
    CONSTRAINT "FK_TaskStatus_User" FOREIGN KEY ("UserId") REFERENCES "User" ("Id")
);

CREATE TABLE "Entry" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SourceId" integer NOT NULL,
    "TransactionTypeId" integer NOT NULL,
    "AccountId" integer NOT NULL,
    "Name" varchar(150) NOT NULL,
    "ImageUrl" varchar(500),
    "Description" varchar(500),
    "Quantity" decimal(10,2) NOT NULL DEFAULT 1,
    "Value" decimal(10,2) NOT NULL,
    "Date" timestamp NOT NULL,
    "CreatedAt" timestamp NOT NULL,
    CONSTRAINT "FK_Entry_Source" FOREIGN KEY ("SourceId") REFERENCES "Source" ("Id"),
    CONSTRAINT "FK_Entry_TransactionType" FOREIGN KEY ("TransactionTypeId") REFERENCES "TransactionType" ("Id"),
    CONSTRAINT "FK_Entry_Account" FOREIGN KEY ("AccountId") REFERENCES "Account" ("Id")
);

CREATE TABLE "Task" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "SourceId" integer,
    "TaskStatusId" integer NOT NULL,
    "Title" varchar(150) NOT NULL,
    "Description" varchar(500),
    "Priority" integer NOT NULL DEFAULT 1,
    "SortOrder" integer NOT NULL DEFAULT 0,
    "DueDate" timestamp,
    "CompletedAt" timestamp,
    "CreatedAt" timestamp NOT NULL,
    CONSTRAINT "FK_Task_User" FOREIGN KEY ("UserId") REFERENCES "User" ("Id"),
    CONSTRAINT "FK_Task_Source" FOREIGN KEY ("SourceId") REFERENCES "Source" ("Id"),
    CONSTRAINT "FK_Task_TaskStatus" FOREIGN KEY ("TaskStatusId") REFERENCES "TaskStatus" ("Id")
);
