CREATE TABLE "User" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" varchar(150) NOT NULL,
    "Email" varchar(255) NOT NULL UNIQUE,
    "PasswordHash" varchar(500) NOT NULL,
    "ProfileImageUrl" varchar(500),
    "CreatedAt" timestamp NOT NULL
);

CREATE TABLE "Source" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "Name" varchar(150) NOT NULL,
    "ImageUrl" varchar(500),
    "CreatedAt" timestamp NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    CONSTRAINT "FK_Source_User" FOREIGN KEY ("UserId") REFERENCES "User" ("Id")
);

CREATE TABLE "TaskStatus" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "Name" varchar(100) NOT NULL,
    "Color" varchar(50) NOT NULL,
    "SortOrder" integer NOT NULL,
    CONSTRAINT "FK_TaskStatus_User" FOREIGN KEY ("UserId") REFERENCES "User" ("Id")
);

CREATE TABLE "Task" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "SourceId" integer,
    "TaskStatusId" integer NOT NULL,
    "Title" varchar(150) NOT NULL,
    "Description" varchar(500),
    "Priority" integer NOT NULL DEFAULT 1,
    "SortOrder" integer NOT NULL DEFAULT 0,
    "DueDate" timestamp,
    "CompletedAt" timestamp,
    "CreatedAt" timestamp NOT NULL,
    CONSTRAINT "FK_Task_User" FOREIGN KEY ("UserId") REFERENCES "User" ("Id"),
    CONSTRAINT "FK_Task_Source" FOREIGN KEY ("SourceId") REFERENCES "Source" ("Id"),
    CONSTRAINT "FK_Task_TaskStatus" FOREIGN KEY ("TaskStatusId") REFERENCES "TaskStatus" ("Id")
);
