Table User {
  Id int [pk, increment]
  Name varchar(150) [not null]
  Email varchar(255) [not null, unique]
  PasswordHash varchar(500) [not null]
  ProfileImageUrl varchar(500)
  CreatedAt datetime [not null]
}

Table Source {
  Id int [pk, increment]
  UserId int [not null]
  Name varchar(150) [not null]
  ImageUrl varchar(500)
  CreatedAt datetime [not null]
  IsActive boolean [not null, default: true]
}

Table Task {
  Id int [pk, increment]
  UserId int [not null]
  SourceId int
  TaskStatusId int [not null]
  Title varchar(150) [not null]
  Description varchar(500)
  Priority int [not null, default: 1]
  SortOrder int [not null, default: 0]
  DueDate datetime
  CompletedAt datetime
  CreatedAt datetime [not null]
}

Table TaskStatus {
  Id int [pk, increment]
  UserId int [not null]
  Name varchar(100) [not null]
  Color varchar(50) [not null]
  SortOrder int [not null]
}

/* RELATIONSHIPS */

Ref: Source.UserId > User.Id

Ref: Task.UserId > User.Id
Ref: Task.SourceId > Source.Id
Ref: Task.TaskStatusId > TaskStatus.Id

Ref: TaskStatus.UserId > User.Id
